# Generated by Django 4.2.7 on 2023-11-14 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм ID')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rate', models.FloatField(default=0, verbose_name='Оценка')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм ID')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Рабочий день')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'График работы мастера',
                'verbose_name_plural': 'Графики работы мастеров',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('duration', models.DurationField(verbose_name='Длительность выполнения (минут)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='VisitJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата посещения')),
                ('visit_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.client', verbose_name='Клиент')),
                ('visit_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.master', verbose_name='Мастер')),
                ('visit_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.service', verbose_name='Оказанная услуга')),
            ],
            options={
                'verbose_name': 'Журнал посещений',
                'verbose_name_plural': 'Журналы посещений',
            },
        ),
        migrations.CreateModel(
            name='MasterScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('is_free', models.BooleanField(default=True, verbose_name='Свободно')),
                ('master_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.masterschedule', verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='servises',
            field=models.ManyToManyField(to='inwork.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='category',
            name='services',
            field=models.ManyToManyField(to='inwork.service', verbose_name='Услуги'),
        ),
    ]
