# Generated by Django 4.2.7 on 2025-04-21 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название рассылки')),
                ('text', models.TextField(help_text='В тексте можно использовать HTML теги и вставлять имя клиента {name}', verbose_name='Текст сообщения')),
                ('photo', models.CharField(blank=True, help_text='Ссылка на фото, не обязательный параметр', max_length=255, null=True, verbose_name='Фото')),
                ('video', models.CharField(blank=True, help_text='Ссылка на видео, не обязательный параметр', max_length=3000, null=True, verbose_name='Видео')),
                ('send_datetime', models.DateTimeField(help_text='Указывайте московское время отправки', verbose_name='Когда отправить')),
                ('filename', models.CharField(help_text='Имя файла csv с выборкой клиентов', max_length=255, verbose_name='Имя файла')),
            ],
            options={
                'verbose_name': 'Ручные рассылки',
                'verbose_name_plural': 'Ручные рассылки',
                'ordering': ('-send_datetime',),
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сертификата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(help_text='Введите цену сертификата в рублях', verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Изображение сертификата')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ФИО клиента', max_length=255, verbose_name='Имя')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Мужчина'), ('w', 'Женщина')], max_length=255, null=True, verbose_name='Пол')),
                ('phone', models.CharField(default='+7', help_text='Введите телефон в формате +79001112233', max_length=12, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате +79001112233', regex='^\\+7\\d{10}$')], verbose_name='Телефон')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм ID')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='Последнее посещение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_blocked', models.BooleanField(blank=True, null=True, verbose_name='Бот заблокирован')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rate', models.FloatField(blank=True, default=0, null=True, verbose_name='Оценка')),
                ('photo', models.ImageField(upload_to='masters/', verbose_name='Фото мастера')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.client', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персона',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('duration', models.IntegerField(verbose_name='Длительность выполнения (минут)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Картинка услуги')),
                ('price', models.IntegerField(verbose_name='Цена(рублей)')),
                ('categories', models.ManyToManyField(to='inwork.categories', verbose_name='Категории')),
                ('persons', models.ManyToManyField(help_text='Выберите для кого доступна услуга', to='inwork.person', verbose_name='Персоны')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='VisitJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата посещения')),
                ('confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждение')),
                ('cancel', models.BooleanField(default=False, verbose_name='Услуга отменена')),
                ('finish', models.BooleanField(default=False, verbose_name='Услуга оказана')),
                ('estimation', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('math_action', models.CharField(choices=[('plus', 'Прибавление'), ('minus', 'Вычитание')], default='plus', max_length=255, verbose_name='Действие')),
                ('math_value', models.IntegerField(blank=True, help_text='Значение должно быть кратным 15', null=True, verbose_name='Значение')),
                ('visit_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.client', verbose_name='Клиент')),
                ('visit_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.master', verbose_name='Мастер')),
                ('visit_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Журнал посещений',
                'verbose_name_plural': 'Журнал посещений',
            },
        ),
        migrations.CreateModel(
            name='ShoppingJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.client', verbose_name='Клиент')),
                ('client_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.certificate', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'Журнал покупок',
                'verbose_name_plural': 'Журналы покупок',
            },
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Рабочий день')),
                ('start_time', models.TimeField(default='10:00:00', verbose_name='Начало работы')),
                ('end_time', models.TimeField(default='21:00:00', verbose_name='Конец работы')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'График работы мастера',
                'verbose_name_plural': 'Графики работы мастеров',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(blank=True, to='inwork.service', verbose_name='Услуги'),
        ),
    ]
