# Generated by Django 4.2.7 on 2025-04-17 18:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [migrations.CreateModel(
        name='Certificate',
        fields=[
            ('id', models.BigAutoField(auto_created=True,
                                       primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(max_length=255,
                                      verbose_name='Название сертификата')),
            ('description', models.TextField(verbose_name='Описание')),
            ('price', models.IntegerField(
                help_text='Введите цену сертификата в рублях', verbose_name='Цена')),
            ('image', models.ImageField(blank=True, null=True,
                                        upload_to='certificates/', verbose_name='Изображение сертификата')),
        ],
        options={
            'verbose_name': 'Сертификат',
            'verbose_name_plural': 'Сертификаты',
        },
    ),
        migrations.CreateModel(
            name='ShoppingJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_uid', models.UUIDField(
                    default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='inwork.client', verbose_name='Клиент')),
                ('client_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='inwork.certificate', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'Журнал покупок',
                'verbose_name_plural': 'Журналы покупок',
            },
    ),
    ]
