# Generated by Django 4.2.7 on 2025-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingjournal',
            name='sum',
            field=models.IntegerField(default=1, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingjournal',
            name='was_used',
            field=models.BooleanField(default=False, verbose_name='Использован?'),
        ),
    ]
