# Generated by Django 4.2.7 on 2025-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0002_shoppingjournal_sum_shoppingjournal_was_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(default='certificates/default.jpg', upload_to='certificates/', verbose_name='Изображение сертификата'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='price',
            field=models.IntegerField(help_text='Введите цену сертификата в рублях', unique=True, verbose_name='Цена'),
        ),
    ]
