# Generated by Django 4.2.7 on 2024-08-14 16:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0002_broadcast_categories_person_сertificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='inwork.сertificate', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'Журнал покупок',
                'verbose_name_plural': 'Журналы покупок',
            },
        ),
    ]
