# Generated by Django 4.2.7 on 2024-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0003_visitjournal_math_action_visitjournal_math_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitjournal',
            name='math_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение'),
        ),
    ]
