# Generated by Django 4.2.7 on 2023-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0004_alter_category_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='Цена(рублей)'),
        ),
    ]
