# Generated by Django 4.2.7 on 2024-03-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0004_alter_visitjournal_math_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitjournal',
            name='math_value',
            field=models.IntegerField(blank=True, help_text='Значение должно быть кратным 15', null=True, verbose_name='Значение'),
        ),
    ]
