# Generated by Django 4.2.7 on 2024-08-14 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0004_broadcast_categories_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingjournal',
            name='email',
            field=models.CharField(
                default=1, max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
