# Generated by Django 4.2.7 on 2023-11-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0005_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
