# Generated by Django 4.2.7 on 2023-11-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0006_remove_service_categories_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='servises',
            new_name='services',
        ),
    ]
