# Generated by Django 4.2.7 on 2024-08-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0005_broadcast_categories_person_and_more'),
        ('inwork', '0006_alter_visitjournal_math_action'),
    ]

    operations = [
    ]
