# Generated by Django 4.2.7 on 2025-04-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0007_merge_20240816_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='сertificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Изображение сертификата'),
        ),
    ]
