# Generated by Django 4.2.7 on 2025-04-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0008_сertificate_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сertificate',
            new_name='Certificate',
        ),
    ]
