# Generated by Django 4.2.7 on 2023-11-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0008_categories_client_description_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitjournal',
            name='estimation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='visitjournal',
            name='finish',
            field=models.BooleanField(default=False, verbose_name='Услуга оказана'),
        ),
        migrations.AlterField(
            model_name='visitjournal',
            name='visit_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.service', verbose_name='Услуга'),
        ),
    ]
