# Generated by Django 4.2.7 on 2023-11-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0009_visitjournal_estimation_visitjournal_finish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(blank=True, to='inwork.master', verbose_name='Мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Оценка'),
        ),
    ]
