# Generated by Django 4.2.7 on 2023-11-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0010_remove_master_services_service_masters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitjournal',
            options={'verbose_name': 'Журнал посещений', 'verbose_name_plural': 'Журнал посещений'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='telegram_id',
            new_name='tg_id',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='telegram_id',
            new_name='tg_id',
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(verbose_name='Длительность выполнения (минут)'),
        ),
    ]
