# Generated by Django 4.2.7 on 2023-11-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0011_alter_visitjournal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitjournal',
            name='date',
            field=models.DateTimeField(verbose_name='Дата посещения'),
        ),
    ]
