# Generated by Django 4.2.7 on 2023-11-28 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0012_alter_visitjournal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(default=1, upload_to='masters/', verbose_name='Фото мастера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='+7', help_text='Введите телефон в формате +79001112233', max_length=12, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате +79001112233', regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
