# Generated by Django 4.2.7 on 2023-11-28 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0013_master_photo_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwork.client', verbose_name='ФИО'),
        ),
    ]
