# Generated by Django 4.2.7 on 2023-11-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0014_alter_master_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='tg_id',
        ),
        migrations.AddField(
            model_name='visitjournal',
            name='cancel',
            field=models.BooleanField(blank=True, null=True, verbose_name='Услуга отменена'),
        ),
        migrations.DeleteModel(
            name='MasterScheduleTime',
        ),
    ]
