# Generated by Django 4.2.7 on 2023-12-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0016_alter_visitjournal_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_blocked',
            field=models.BooleanField(blank=True, null=True, verbose_name='Бот заблокирован'),
        ),
    ]
