# Generated by Django 4.2.7 on 2023-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0017_client_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее посещение'),
        ),
    ]
