# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0018_client_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='masters',
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(blank=True, to='inwork.service', verbose_name='Услуги'),
        ),
    ]
