# Generated by Django 4.2.7 on 2023-12-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0019_remove_service_masters_master_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персона',
            },
        ),
    ]
