# Generated by Django 4.2.7 on 2023-12-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0020_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='persons',
            field=models.ManyToManyField(help_text='Если никого не выбрать, услуга будет доступна для всех', to='inwork.person', verbose_name='Персоны'),
        ),
    ]
