# Generated by Django 4.2.7 on 2023-12-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0021_service_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitjournal',
            name='confirmation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(to='inwork.categories', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='persons',
            field=models.ManyToManyField(help_text='Выберите для кого доступна услуга', to='inwork.person', verbose_name='Персоны'),
        ),
    ]
