# Generated by Django 4.2.7 on 2024-01-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0023_visitjournal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Картинка услуги'),
        ),
    ]
