# Generated by Django 4.2.7 on 2024-01-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0024_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='services/', verbose_name='Картинка услуги', width_field=100),
        ),
    ]
