# Generated by Django 4.2.7 on 2024-02-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0027_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
