# Generated by Django 4.2.7 on 2024-02-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0028_delete_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitjournal',
            name='visit_service',
        ),
        migrations.AddField(
            model_name='visitjournal',
            name='visit_service',
            field=models.ManyToManyField(to='inwork.service', verbose_name='Услуга'),
        ),
    ]
