# Generated by Django 4.2.4 on 2024-02-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0029_remove_visitjournal_visit_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitjournal',
            name='visit_service',
        ),
        migrations.AddField(
            model_name='visitjournal',
            name='visit_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inwork.service', verbose_name='Услуга'),
            preserve_default=False,
        ),
    ]
