# Generated by Django 4.2.7 on 2024-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwork', '0031_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Мужчина'), ('w', 'Женщина')], max_length=255, null=True, verbose_name='Пол'),
        ),
    ]
